
import java.awt.Color;
import java.awt.Dimension;
import java.awt.GridLayout;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.Box;
import javax.swing.BoxLayout;
import javax.swing.JButton;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JTextField;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author hp
 */
public class NimGameV2 extends javax.swing.JFrame {
private JButton[] Buttons;
String delete = "ready";
    /**
     * Creates new form NewJFrame
     */
    public NimGameV2() {
         initComponents();
        // 3 columns, 0 rows to start
//        createPileButtons(3); // Initial call to create 3 buttons
//        createPileButtons(7); // Second call to create 7 buttons
//        // Add more calls to createPileButtons with different numbers as needed
//        pack(); // Pack the frame to ensure proper layout
//        setLocationRelativeTo(null); // Center the frame
//        setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        
        
    }
private void createPileButtons(int[] buttonsInEachRow) {
    JPanel jPanel1 = new JPanel(); // Assuming jPanel1 is your main panel
    jPanel1.setLayout(new BoxLayout(jPanel1, BoxLayout.Y_AXIS)); // Use BoxLayout for vertical arrangement

    for (int row = 0; row < buttonsInEachRow.length; row++) {
        JPanel rowPanel = new JPanel();
        for (int i = 0; i < buttonsInEachRow[row]; i++) {
            JButton button = new JButton("Button" + (i + 1));
            button.setToolTipText(Integer.toString(row));
            button.addActionListener(new ActionListener() {
                @Override
                public void actionPerformed(ActionEvent e) {
                    // Handle button click event (e.g., selecting a pile).
                    if(delete.compareToIgnoreCase("ready")==0){
                        button.setVisible(false);
                        delete=button.getToolTipText();
                    }
                    else if(button.getToolTipText().compareToIgnoreCase(delete)==0){
                        button.setVisible(false);
                    }
                    
                }
            });
            rowPanel.add(button); // Add the button to the rowPanel
        }

        // Add the rowPanel to the main panel
        jPanel1.add(rowPanel);

        // Add an empty spacer to create a new line
        jPanel1.add(Box.createRigidArea(new Dimension(0,5)));
       // jPanel1.add(Box.createRigidArea(new Dimension(0, 10));
    }

    JButton startButton = new JButton("PC Turn");
    startButton.setBackground(Color.blue);
    startButton.addActionListener(new ActionListener() {
                @Override
                public void actionPerformed(ActionEvent e) {
                    // Handle button click event (e.g., selecting a pile).
                   delete="ready";
                    
                }
            });
    jPanel1.add(startButton);

    // Add jPanel1 to your main frame or container
    // For example, if you're using a JFrame:
    JFrame frame = new JFrame("Your Frame Title");
    frame.add(jPanel1);
    frame.setLocationRelativeTo(null);
    frame.pack();
    frame.setVisible(true);
}




    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NimGame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NimGame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NimGame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NimGame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                NimGameV2 nimGame = new NimGameV2(); // Create an instance of the NimGame class
         //   nimGame.setVisible(true); // Display the GUI
            int numPiles []= {3,5,7}; // Change this to the desired number of piles
            nimGame.createPileButtons(numPiles); 
            // nimGame.createPileButtons(numPiles); 
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
